import { describe, expect, it } from 'vitest';
import { RecertificationService } from '../domain.mjs';
const fixedNow = () => new Date('2026-08-25T10:00:00.000Z');
const input = () => ({ name: 'Q3 supplier certificate access', owner: 'owner@buyer.test', dueAt: '2026-08-30T10:00:00.000Z', assignments: [{ evidenceId: 'evidence-658', subject: 'analyst@buyer.test', manager: 'manager@buyer.test', entitlement: 'view certificate vault' }, { evidenceId: 'evidence-659', subject: 'buyer@buyer.test', manager: 'manager2@buyer.test', entitlement: 'export compliance packet' }] });
describe('RecertificationService', () => {
  it('launches and retains a reviewed assignment', () => { const service = new RecertificationService(undefined, () => {}, fixedNow); const campaign = service.launch(input()); expect(service.attestation(campaign.id, 'assignment-1', 'manager@buyer.test', 'retain', 'needed for supplier review').decision).toBe('retain'); });
  it('rejects campaigns with no assignments', () => expect(() => new RecertificationService(undefined, () => {}, fixedNow).launch({ ...input(), assignments: [] })).toThrow('assignments'));
  it('blocks attestation by a non-manager', () => { const service = new RecertificationService(undefined, () => {}, fixedNow); const campaign = service.launch(input()); expect(() => service.attestation(campaign.id, 'assignment-1', 'other@buyer.test', 'remove', 'no')).toThrow('assigned manager'); });
  it('rejects an invalid decision', () => { const service = new RecertificationService(undefined, () => {}, fixedNow); const campaign = service.launch(input()); expect(() => service.attestation(campaign.id, 'assignment-1', 'manager@buyer.test', 'maybe', 'unclear')).toThrow('retain or remove'); });
  it('escalates overdue pending assignments', () => { let current = new Date('2026-08-25T08:00:00.000Z'); const service = new RecertificationService(undefined, () => {}, () => current); const campaign = service.launch({ ...input(), dueAt: '2026-08-25T09:00:00.000Z' }); current = new Date('2026-08-25T10:00:00.000Z'); expect(service.escalateDue()).toHaveLength(2); expect(campaign.assignments[0].status).toBe('escalated'); });
  it('persists mutations and closes attested campaign', () => { let writes = 0; const service = new RecertificationService(undefined, () => { writes += 1; }, fixedNow); const campaign = service.launch({ ...input(), assignments: [input().assignments[0]] }); service.attestation(campaign.id, 'assignment-1', 'manager@buyer.test', 'remove', 'role reassigned'); expect(service.close(campaign.id, 'owner@buyer.test').status).toBe('closed'); expect(writes).toBe(3); });
});
