const required = (value, field) => { if (!value || !String(value).trim()) throw new Error(`${field} is required`); };
const dateOf = (value, field) => { const date = new Date(value); if (Number.isNaN(date.valueOf())) throw new Error(`${field} must be a valid timestamp`); return date; };
export class RecertificationService {
  constructor(state = { campaigns: [], audit: [] }, persist = () => {}, now = () => new Date()) { this.state = { campaigns: state.campaigns ?? [], audit: state.audit ?? [] }; this.persist = persist; this.now = now; }
  id(prefix, list) { return `${prefix}-${list.length + 1}`; }
  event(campaignId, action, actor, detail = '') { this.state.audit.push({ id: this.id('audit', this.state.audit), campaignId, action, actor, detail, at: this.now().toISOString() }); }
  save() { this.persist(this.state); }
  launch(input) { for (const field of ['name', 'owner', 'dueAt']) required(input[field], field); const dueAt = dateOf(input.dueAt, 'dueAt'); if (dueAt <= this.now()) throw new Error('dueAt must be in the future'); if (!Array.isArray(input.assignments) || !input.assignments.length) throw new Error('assignments must include at least one access record'); const assignments = input.assignments.map((item, index) => { for (const field of ['evidenceId', 'subject', 'manager', 'entitlement']) required(item[field], `assignments[${index}].${field}`); return { id: `assignment-${index + 1}`, ...item, status: 'pending', decision: null, rationale: null }; }); const item = { id: this.id('campaign', this.state.campaigns), name: input.name, owner: input.owner, dueAt: dueAt.toISOString(), assignments, status: 'open' }; this.state.campaigns.push(item); this.event(item.id, 'launched', input.owner, `${assignments.length} access records`); this.save(); return item; }
  find(id) { const item = this.state.campaigns.find((candidate) => candidate.id === id); if (!item) throw new Error('recertification campaign not found'); return item; }
  attestation(id, assignmentId, actor, decision, rationale) { const item = this.find(id); required(actor, 'actor'); required(rationale, 'rationale'); if (!['retain', 'remove'].includes(decision)) throw new Error('decision must be retain or remove'); if (item.status !== 'open') throw new Error('only open campaigns can be attested'); const assignment = item.assignments.find((candidate) => candidate.id === assignmentId); if (!assignment) throw new Error('assignment not found'); if (assignment.status !== 'pending') throw new Error('only pending assignments can be attested'); if (assignment.manager !== actor) throw new Error('only the assigned manager can attest'); assignment.status = 'attested'; assignment.decision = decision; assignment.rationale = rationale; this.event(id, decision === 'retain' ? 'retained' : 'removed', actor, assignmentId); this.save(); return assignment; }
  escalateDue(actor = 'system') { const now = this.now(); const changed = []; for (const item of this.state.campaigns.filter((candidate) => candidate.status === 'open' && dateOf(candidate.dueAt, 'dueAt') <= now)) { for (const assignment of item.assignments.filter((candidate) => candidate.status === 'pending')) { assignment.status = 'escalated'; changed.push({ campaignId: item.id, assignmentId: assignment.id }); this.event(item.id, 'escalated', actor, assignment.id); } } if (changed.length) this.save(); return changed; }
  close(id, actor) { const item = this.find(id); required(actor, 'actor'); if (item.owner !== actor) throw new Error('only the campaign owner can close'); if (item.status !== 'open') throw new Error('only open campaigns can be closed'); if (item.assignments.some((assignment) => !['attested', 'escalated'].includes(assignment.status))) throw new Error('all assignments must be attested or escalated before closing'); item.status = 'closed'; this.event(id, 'closed', actor, `${item.assignments.length} assignments`); this.save(); return item; }
  auditFor(id) { this.find(id); return this.state.audit.filter((event) => event.campaignId === id); }
}

